In [2221]:
import os
os.getcwd()

'D:\\ML certification files\\submission\\Mercedes-Benz Greener Manufacturing'

In [2222]:
os.chdir("D:\\ML certification files\submission\Mercedes-Benz Greener Manufacturing")

In [2223]:
import pandas as pd
import numpy as np

In [2224]:
train=pd.read_csv("train.csv")
train.drop("ID",axis=1,inplace=True)
train.head(3)

y  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0  130.81   k  v  at  a  d  u  j  o    0  ...     0     0     1     0     0   
1   88.53   k  t  av  e  d  y  l  o    0  ...     1     0     0     0     0   
2   76.26  az  w   n  c  d  x  j  x    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  

[3 rows x 377 columns]

In [2225]:
test=pd.read_csv("test.csv")
test.drop("ID",axis=1,inplace=True)
test.head(3)

X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0  az  v   n  f  d  t  a  w    0    0  ...     0     0     0     1     0   
1   t  b  ai  a  d  b  g  y    0    0  ...     0     0     1     0     0   
2  az  v  as  f  d  a  j  j    0    0  ...     0     0     0     1     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  

[3 rows x 376 columns]

In [2226]:
train.describe()

y          X10     X11          X12          X13  \
count  4209.000000  4209.000000  4209.0  4209.000000  4209.000000   
mean    100.669318     0.013305     0.0     0.075077     0.057971   
std      12.679381     0.114590     0.0     0.263547     0.233716   
min      72.110000     0.000000     0.0     0.000000     0.000000   
25%      90.820000     0.000000     0.0     0.000000     0.000000   
50%      99.150000     0.000000     0.0     0.000000     0.000000   
75%     109.010000     0.000000     0.0     0.000000     0.000000   
max     265.320000     1.000000     0.0     1.000000     1.000000   

               X14          X15          X16          X17          X18  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.428130     0.000475     0.002613     0.007603     0.007840  ...   
std       0.494867     0.021796     0.051061     0.086872     0.088208  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       1.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 369 columns]

In [2227]:
test.describe()

X10          X11          X12          X13          X14  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.019007     0.000238     0.074364     0.061060     0.427893   
std       0.136565     0.015414     0.262394     0.239468     0.494832   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               X15          X16          X17          X18          X19  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.000713     0.002613     0.008791     0.010216     0.111665  ...   
std       0.026691     0.051061     0.093357     0.100570     0.314992  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.325968     0.049656     0.311951     0.019244     0.011879   
std       0.468791     0.217258     0.463345     0.137399     0.108356   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.008791     0.000475     0.000713     0.001663  
std       0.089524     0.093357     0.021796     0.026691     0.040752  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 368 columns]

In [2228]:
train.isnull().sum()

y       0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

In [2229]:
train_target=train["y"]
train_data=train.drop("y",axis=1)

In [2230]:
train_data.head(3)

X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0   k  v  at  a  d  u  j  o    0    0  ...     0     0     1     0     0   
1   k  t  av  e  d  y  l  o    0    0  ...     1     0     0     0     0   
2  az  w   n  c  d  x  j  x    0    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  

[3 rows x 376 columns]

In [2231]:
train_data.dtypes.head(20)

X0     object
X1     object
X2     object
X3     object
X4     object
X5     object
X6     object
X8     object
X10     int64
X11     int64
X12     int64
X13     int64
X14     int64
X15     int64
X16     int64
X17     int64
X18     int64
X19     int64
X20     int64
X21     int64
dtype: object

In [2232]:
train_data2=train_data.select_dtypes(include="object")

In [2233]:
train_data1=train_data.select_dtypes(exclude="object")

In [2234]:
## x0,x1,x2,x3,x4,x5,x6,x8 are all objects,and we will later apply label encoder on them 
## first lets remove zero variance columns(variables)

In [2235]:
from sklearn.feature_selection import VarianceThreshold

In [2236]:
variance= VarianceThreshold(threshold=0)

In [2237]:
train_data1.describe()

X10     X11          X12          X13          X14  \
count  4209.000000  4209.0  4209.000000  4209.000000  4209.000000   
mean      0.013305     0.0     0.075077     0.057971     0.428130   
std       0.114590     0.0     0.263547     0.233716     0.494867   
min       0.000000     0.0     0.000000     0.000000     0.000000   
25%       0.000000     0.0     0.000000     0.000000     0.000000   
50%       0.000000     0.0     0.000000     0.000000     0.000000   
75%       0.000000     0.0     0.000000     0.000000     1.000000   
max       1.000000     0.0     1.000000     1.000000     1.000000   

               X15          X16          X17          X18          X19  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.000475     0.002613     0.007603     0.007840     0.099549  ...   
std       0.021796     0.051061     0.086872     0.088208     0.299433  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 368 columns]

In [2238]:
train_data1.var().sort_values().head(20)

X330    0.000000
X297    0.000000
X268    0.000000
X290    0.000000
X235    0.000000
X347    0.000000
X107    0.000000
X233    0.000000
X289    0.000000
X93     0.000000
X11     0.000000
X293    0.000000
X257    0.000238
X207    0.000238
X280    0.000238
X288    0.000238
X39     0.000238
X33     0.000238
X190    0.000238
X270    0.000238
dtype: float64

In [2239]:
check=train_data1.var().sort_values().head(20)
check>0

X330    False
X297    False
X268    False
X290    False
X235    False
X347    False
X107    False
X233    False
X289    False
X93     False
X11     False
X293    False
X257     True
X207     True
X280     True
X288     True
X39      True
X33      True
X190     True
X270     True
dtype: bool

In [2240]:
## we can see that there are 12 columns with variance as zero. lets drop them and select other columns.and create new data set train_data_zero_variance 

In [2241]:
train_data1_zero_variance=variance.fit_transform(train_data.iloc[:,11:])
train_data1_zero_variance

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [2242]:
## now we will apply label encoder on object variables

In [2243]:
labelled_data=train_data2.iloc[:,0:8]
labelled_data.head()

X0 X1  X2 X3 X4 X5 X6 X8
0   k  v  at  a  d  u  j  o
1   k  t  av  e  d  y  l  o
2  az  w   n  c  d  x  j  x
3  az  t   n  f  d  x  l  e
4  az  v   n  f  d  h  d  n

In [2244]:
labelled_data.nunique()

X0    47
X1    27
X2    44
X3     7
X4     4
X5    29
X6    12
X8    25
dtype: int64

In [2245]:
from sklearn.preprocessing import LabelEncoder

In [2246]:
label=LabelEncoder

In [2247]:
new_labelled_data=labelled_data.apply(label().fit_transform)
new_labelled_data.head()

X0  X1  X2  X3  X4  X5  X6  X8
0  32  23  17   0   3  24   9  14
1  32  21  19   4   3  28  11  14
2  20  24  34   2   3  27   9  23
3  20  21  34   5   3  27  11   4
4  20  23  34   5   3  12   3  13

In [2248]:
new_labelled_data.var()

X0    188.741938
X1     72.777974
X2    118.808135
X3      3.027295
X4      0.005461
X5     68.076236
X6      8.508730
X8     49.531868
dtype: float64

In [2249]:
final_train_data_zero_variance=pd.DataFrame(train_data_zero_variance)

In [2250]:
final_train_data_zero_variance.head()

0    1    2    3    4    5    6    7    8    9    ...  344  345  346  347  \
0    1    0    0    0    0    1    0    0    1    0  ...    0    0    1    0   
1    0    0    0    0    0    1    0    0    0    0  ...    1    0    0    0   
2    0    0    0    0    1    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   348  349  350  351  352  353  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    1    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 354 columns]

In [2251]:
final_train_data=pd.concat([new_labelled_data,final_train_data_zero_variance],axis=1)

In [2252]:
final_train_data.head()

X0  X1  X2  X3  X4  X5  X6  X8  0  1  ...  344  345  346  347  348  349  \
0  32  23  17   0   3  24   9  14  1  0  ...    0    0    1    0    0    0   
1  32  21  19   4   3  28  11  14  0  0  ...    1    0    0    0    0    0   
2  20  24  34   2   3  27   9  23  0  0  ...    0    0    0    0    0    0   
3  20  21  34   5   3  27  11   4  0  0  ...    0    0    0    0    0    0   
4  20  23  34   5   3  12   3  13  0  0  ...    0    0    0    0    0    0   

   350  351  352  353  
0    0    0    0    0  
1    0    0    0    0  
2    1    0    0    0  
3    0    0    0    0  
4    0    0    0    0  

[5 rows x 362 columns]

In [2253]:
final_train_data.isnull().any()

X0     False
X1     False
X2     False
X3     False
X4     False
       ...  
349    False
350    False
351    False
352    False
353    False
Length: 362, dtype: bool

In [2254]:
## follow same steps for test data

In [2255]:
test.head()

X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0  az  v   n  f  d  t  a  w    0    0  ...     0     0     0     1     0   
1   t  b  ai  a  d  b  g  y    0    0  ...     0     0     1     0     0   
2  az  v  as  f  d  a  j  j    0    0  ...     0     0     0     1     0   
3  az  l   n  f  d  z  l  n    0    0  ...     0     0     0     1     0   
4   w  s  as  c  d  y  i  m    0    0  ...     1     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 376 columns]

In [2256]:
test.nunique()

X0      49
X1      27
X2      45
X3       7
X4       4
        ..
X380     2
X382     2
X383     2
X384     2
X385     2
Length: 376, dtype: int64

In [2257]:
test.isnull().any()

X0      False
X1      False
X2      False
X3      False
X4      False
        ...  
X380    False
X382    False
X383    False
X384    False
X385    False
Length: 376, dtype: bool

In [2258]:
test.dtypes

X0      object
X1      object
X2      object
X3      object
X4      object
         ...  
X380     int64
X382     int64
X383     int64
X384     int64
X385     int64
Length: 376, dtype: object

In [2259]:
test1=test.select_dtypes(exclude="object")
test2=test.select_dtypes(include="object")

In [2260]:
test1.var().sort_values()

X295    0.000000
X369    0.000000
X296    0.000000
X257    0.000000
X258    0.000000
          ...   
X194    0.249053
X337    0.249332
X191    0.249489
X362    0.249738
X127    0.249866
Length: 368, dtype: float64

In [2261]:
check1=test1.var().sort_values().head(20)
check1>0

X295    False
X369    False
X296    False
X257    False
X258    False
X278     True
X233     True
X280     True
X290     True
X293     True
X330     True
X235     True
X288     True
X210     True
X297     True
X105     True
X124     True
X259     True
X372     True
X190     True
dtype: bool

In [2262]:
test_data_zero_variance= variance.fit_transform(test1.iloc[:,9:])
test_data_zero_variance

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [2263]:
final_test_data_zero_variance=pd.DataFrame(test_data_zero_variance)

In [2264]:
final_test_data_zero_variance.head()

0    1    2    3    4    5    6    7    8    9    ...  344  345  346  347  \
0    0    0    0    0    0    0    0    1    1    1  ...    0    0    0    1   
1    1    0    0    0    0    0    0    1    0    0  ...    0    0    1    0   
2    0    0    0    0    0    0    0    1    0    1  ...    0    0    0    1   
3    0    0    0    0    0    0    0    1    1    1  ...    0    0    0    1   
4    0    0    0    0    0    0    0    1    0    0  ...    1    0    0    0   

   348  349  350  351  352  353  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 354 columns]

In [2265]:
labelled_data1=test2.iloc[:,0:8]
labelled_data1.head()

X0 X1  X2 X3 X4 X5 X6 X8
0  az  v   n  f  d  t  a  w
1   t  b  ai  a  d  b  g  y
2  az  v  as  f  d  a  j  j
3  az  l   n  f  d  z  l  n
4   w  s  as  c  d  y  i  m

In [2266]:
test_labelled=labelled_data1.apply(label().fit_transform)
test_labelled.head()

X0  X1  X2  X3  X4  X5  X6  X8
0  21  23  34   5   3  26   0  22
1  42   3   8   0   3   9   6  24
2  21  23  17   5   3   0   9   9
3  21  13  34   5   3  31  11  13
4  45  20  17   2   3  30   8  12

In [2267]:
final_test_data=pd.concat([test_labelled,final_test_data_zero_variance],axis=1)
final_test_data.head()

X0  X1  X2  X3  X4  X5  X6  X8  0  1  ...  344  345  346  347  348  349  \
0  21  23  34   5   3  26   0  22  0  0  ...    0    0    0    1    0    0   
1  42   3   8   0   3   9   6  24  1  0  ...    0    0    1    0    0    0   
2  21  23  17   5   3   0   9   9  0  0  ...    0    0    0    1    0    0   
3  21  13  34   5   3  31  11  13  0  0  ...    0    0    0    1    0    0   
4  45  20  17   2   3  30   8  12  0  0  ...    1    0    0    0    0    0   

   350  351  352  353  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  

[5 rows x 362 columns]

In [2268]:
final_test_data.columns

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',    0,    1,
       ...
        344,  345,  346,  347,  348,  349,  350,  351,  352,  353],
      dtype='object', length=362)

In [2269]:
x=final_train_data
y=train["y"]

In [2270]:
from sklearn.model_selection import train_test_split

In [2271]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [2272]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((2946, 362), (1263, 362), (2946,), (1263,))

In [2273]:
## performing dimentionality reduction

In [2274]:
from sklearn.decomposition import PCA
pca=PCA(n_components=12)

In [2275]:
x_train=pca.fit_transform(x_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [2276]:
x_test=pca.transform(x_test)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [2277]:
final_test_data=pca.transform(final_test_data)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [2278]:
from xgboost import XGBRegressor

In [2279]:
xg=XGBRegressor(random_state=1)

In [2280]:
model=xg.fit(x_train,y_train)

In [2281]:
test_pred=xg.predict(x_test)

In [2282]:
test_pred

array([ 79.96207 , 102.67406 , 111.894875, ..., 117.33982 ,  79.71137 ,
        94.07381 ], dtype=float32)

In [2283]:
train_pred=xg.predict(x_train)

In [2284]:
train_pred

array([102.53908 ,  95.43286 , 103.90513 , ..., 110.196236, 141.40051 ,
       105.481705], dtype=float32)

In [2285]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [2286]:
 r2_score(y_test,test_pred)

0.43692589908734425

In [2287]:
r2_score(y_train,train_pred)

0.9310871526833981

In [2288]:
final_test_data_prediction=model.predict(final_test_data)
final_test_data_prediction

array([101.769135, 102.2388  ,  91.39219 , ..., 107.87216 , 102.8382  ,
        89.37887 ], dtype=float32)